### ISSUE TITLE
.whiteboard files are downloaded instead of opened

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [nextcloud/whiteboard#174] opened 2024-09-19 04:28 UTC
![1](https://github.com/user-attachments/assets/1e5f077c-6457-44b1-87cd-62f5098d59e4)
I have installed whiteboard 1.0.2 and run it in within a docker-container and apache reverse proxy.
My nextcloud (version 30) runs at https://www.mydomain/nextcloud.
The configuration seems fine, as the app configuration page of whiteboard shows all green and successful.
If I create a new whiteboard, my instance is starting to download it instead of opening it in whiteboard.
In my ./config/mimetypealiases.json  I cannot fine the .whiteboard extension even after installing whiteboard 1.0.2.
What could be the issue?

The nextcloud logs show no issues.

**Comment by architectonio** [comment] 2024-09-19 14:22
On my NextCloud Instance (29.0.7 + Whiteboard 1.0.2), I notice exactly the same behavior.
As soon as the file is created it is immediately downloaded and by clicking on it, it is downloaded again.....and again

**Comment by architectonio** [comment] 2024-09-19 15:48
> Please read the Known Issues section from the README file. It helps me to solve this behavior.

Thanks for replying.
I did follow the procedure
"sudo -u www-data php occ maintenance:mimetype:update-db"
Added mimetype "application/x-blender" to database
Added mimetype "image/bpg" to database
Added mimetype "video/dv" to database
Added mimetype "application/x-fictionbook+xml" to database
Added mimetype "image/heif" to database
Added mimetype "text/impress" to database
Added mimetype "text/x-ldif" to database
Added mimetype "video/mp2t" to database
Added mimetype "video/MP2T" to database
Added mimetype "application/x-iwork-numbers-sffnumbers" to database
Added mimetype "application/vnd.oasis.opendocument.formula" to database
Added mimetype "application/x-iwork-pages-sffpages" to database
Added mimetype "application/vnd.ms-powerpoint.template.macroEnabled.12" to database
Added mimetype "application/vnd.ms-powerpoint.addin.macroEnabled.12" to database
Added mimetype "application/vnd.ms-powerpoint.slideshow.macroEnabled.12" to database
Added mimetype "text/reveal" to database
Added mimetype "application/rss+xml" to database
Added mimetype "application/sgf" to database
Added mimetype "image/sgi" to database
Added mimetype "application/vnd.ms-visio.drawing.macroEnabled.12" to database
Added mimetype "application/vnd.ms-visio.stencil.macroEnabled.12" to database
Added mimetype "application/vnd.ms-visio.template.macroEnabled.12" to database
Added mimetype "application/vnd.ms-visio.template" to database
Added mimetype "audio/webm" to database
Added mimetype "application/vnd.ms-excel.addin.macroEnabled.12" to database
Added mimetype "application/vnd.ms-excel.template.macroEnabled.12" to database
Added mimetype "model/mtl" to database
Added mimetype "application/x-compress" to database
Added 28 new mimetypes
Updated 0 filecache rows

and then
"sudo -u www-data php occ maintenance:mimetype:update-js"
mimetypelist.js is updated

Unfortunately the issue is persisting.

I guess the appropriate setting "**.witheboard**"in the DB and either **mimetypealiases.json** or **mymetypemapping.json** is missing or still wrong.
For instance in my **mymetypemapping.json** i have
  **"wbr": [
        "application/whiteboard"
    ],
    "whiteboard": [
        "application/spacedeck"
    ],**
I guess must remove the ### wbr part and replace###  spacedeck with ### whiteboard....
    "whiteboard": [
        "application/whiteboard"
    ],

**Comment by ralfi** [comment] 2024-09-19 16:16
Plesse remove everything with wbr and whiteboard from the files if exist, then do the occ commands.

**Comment by architectonio** [comment] 2024-09-19 17:09
Hi @ralfi i just did it and now works!
Thanks everybody for helping.

**Comment by GVLLIFESTYLE** [comment] 2024-09-20 04:45
I see the mistake in the readme. There is written

> If the [integration_whiteboard](https://github.com/nextcloud/integration_whiteboard) app was previously installed there might be a leftover non-standard mimetype configured. In this case opening the whiteboard may fail and a file is downloaded instead. Make sure to remove any entry in config/mimetypealiases.json mentioning whiteboard and run occ maintenance:mimetype:update-db and occ maintenance:mimetype:update-js.

But the main file I had to change was mimetypemapping.json . Now it does not download the files anymore.

I got another error though:

![image](https://github.com/user-attachments/assets/89699492-ed33-46ec-b6db-1f20e659822a)

![image](https://github.com/user-attachments/assets/83dc8b2e-af96-46b9-b30a-515e70dbb34f)

**Comment by kinimodmeyer** [comment] 2024-09-22 12:51
> Plesse remove everything with wbr and whiteboard from the files if exist, then do the occ commands. This works for me and exactly this tells you the README file.

This seems not to make the trick for everybody. In my case i still have the mentioned issue above.
mimetypealiases.json & mimetypemapping.json have no whiteboard reference.

**Comment by leo-333** [comment] 2024-09-26 10:36
Yes i have also the same behaviour. I have nextcloud 30 with php8.2-fpm installed. The apache2 server is configured like the documentation says. I have tried the latest build from the whiteboard-server and i get also the 404 error you mentionend @kinimodmeyer

**Comment by tetebueno** [comment] 2024-10-02 16:05
I was victim of this issue and the steps mentioned on the README page didn't work for me. What did work was the following:
* Add the following entry to `resources/config/mimetypealiases.dist.json` (check the ending comma if it's not the last entry):
```json
  "application/vnd.excalidraw+json": "whiteboard",
```
* * Add the following entry to `resources/config/mimetypemapping.dist.json` (check the ending comma if it's not the last entry):
```json
  "whiteboard": ["application/vnd.excalidraw+json"],
```
* Run the mentioned commands:
```console
$ php occ maintenance:mimetype:update-db -vvv; php occ maintenance:mimetype:update-js -vvv
```
Hope it helps.

P.S.: awesome project. Thanks a lot.

**Comment by GVLLIFESTYLE** [comment] 2024-10-08 13:35
Thanks, but the issue with the 404 Error is still persisting also with version: 1.0.3

**Comment by juliushaertl** [comment] 2024-10-14 14:34
If you get that 404 and have Nextcloud installed in a subdirectory this might be fixed by 1.0.4, with #158

**Comment by GVLLIFESTYLE** [comment] 2024-10-16 11:19
works now somehow after latest update.

**Comment by juliushaertl** [comment] 2024-10-16 11:59
Thanks for reporting back, then it was related to the issue fixed in #158

**Closed by juliushaertl** 2024-10-16 11:59 UTC
Labels: bug

**Comment by matrixes** [comment] 2024-11-25 14:55
This section did not work for me: https://github.com/nextcloud/whiteboard#known-issues
This, however, worked flawlessly: https://github.com/nextcloud/whiteboard/issues/174#issuecomment-2389055406

Whiteboard: 1.0.4
NC: 29.0.4

Other than that, everything works 🚀 . I'm really grateful for this integration.

**Comment by juliusknorr** [comment] 2024-11-25 16:40
>  NC: 29.0.4

Your Nextcloud version is quite behind. Those types would be introduced with 29.0.5 (https://github.com/nextcloud/server/pull/46752).

**Comment by leo-333** [comment] 2025-01-13 14:43
its working for me too with new version. thank you.

**Comment by ChrWieg** [comment] 2025-03-29 21:16
This solved the problem for me:
`occ maintenance:mimetype:update-db --repair-filecache`
Then reload the page in the browser (Strg.-F5)

Solution from: [https://www.c-rieger.de/nextcloud-whiteboard/](Carsten Riegerl)
