### ISSUE TITLE
Nextcloud subpath support

### ISSUE THREAD

**Issue by robertmx** [nextcloud/whiteboard#160] opened 2024-09-15 12:37 UTC
It seems that the whiteboard server or app does not support nextcloud subpath deployments. I have a nextcloud server running under https://example.com/nextcloud/*. During loading of the whiteboard I see requests to https://example.com/* which obviously can not succeed.

**Comment by juliushaertl** [comment] 2024-09-16 09:54
Did you configure the full URL including the subpath in the as `NEXTCLOUD_URL` in the backend server deployment?

**Comment by robertmx** [comment] 2024-09-16 13:19
Thanks for coming back to this issue. Yes I did use the full subpath.

```
# Nextcloud config (using internal docker container name)
./occ config:app:set whiteboard collabBackendUrl --value="http://nextcloud-whiteboard:3002"
./occ config:app:set whiteboard jwt_secret_key --value="{{ NEXTCLOUD_WHITEBOARD_SECRET }}"

# Whiteboard Docker env (via Ansible)
    env:
      NEXTCLOUD_URL: "https://example.com/nextcloud"
      JWT_SECRET_KEY: "{{ NEXTCLOUD_WHITEBOARD_SECRET }}"

```

**Comment by juliushaertl** [comment] 2024-09-16 13:33
I just tried this and for me configuring in a subpath works fine.

Can you share how you noticed the calls to example.com instead of example.com/whiteboard?

Also is http://nextcloud-whiteboard:3002 reachable from your browser? The configured collabBackendUrl needs to be reachable from any browser that accesses a whiteboard

**Comment by d3xt3r01** [comment] 2024-10-09 10:56
I also have it in a subpath.

The way I noticed the issue is that I created a test.whiteboard and when clicking it seems to try to load `/index.php/apps/whiteboard/3256079/token` instead of `/nextcloud/index.php/apps/whiteboard/3256079/token` like all the others in the chrome network tab.
The request returns a 404 so of course everything fails.

**Comment by juliushaertl** [comment] 2024-10-09 11:23
Thanks for sharing that insight, I've pushed a fix for this in https://github.com/nextcloud/whiteboard/pull/209. Apparently my test setup allowed both and I only checked for the callback URL.

**Closed** 2024-10-14 09:42 UTC
Labels: bug, 2. developing
